source 'git@github.com:NoryCao/cjspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ZSExtension_Example' do
  pod 'ZSExtension', :path => '../'

  target 'ZSExtension_Tests' do
    inherit! :search_paths

    
  end
end
